# Generated by Django 5.0 on 2023-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0004_alter_customuser_options_alter_namozvaqti_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mintaqa',
            name='viloyat',
            field=models.CharField(choices=[('1', 'Toshkent shaxri'), ('2', 'Andijon'), ('3', 'Buxoro'), ('4', 'Fargʻona'), ('5', 'Jizzax'), ('6', 'Namangan'), ('7', 'Navoiy'), ('8', 'Qashqadaryo'), ('9', 'Qoraqalpogʻiston'), ('10', 'Samarqand'), ('11', 'Sirdaryo'), ('12', 'Surxondaryo'), ('13', 'Toshkent viloyati'), ('14', 'Xorazm'), ('99', 'Boshqa')], help_text='Mintaqa joylashgan viloyat', max_length=255, verbose_name='Viloyat'),
        ),
    ]
