# Generated by Django 5.0 on 2023-12-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0005_alter_mintaqa_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_type',
            field=models.CharField(choices=[('region', 'Viloyat/Shaxar adminstratori'), ('district', 'Tuman adminstratori'), ('masjid', 'Masjid adminstratori')], max_length=255, null=True, verbose_name='Adminstrator turi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Adminstratorga biriktiriladigan tuman', null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='masjid',
            field=models.ForeignKey(blank=True, help_text='Adminstratorga biriktiriladigan masjid', null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.masjid', verbose_name='Masjid'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Adminstratorga biriktiriladigan viloyat/shaxar', null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.region', verbose_name='Viloyat/Shaxar'),
        ),
    ]
