# Generated by Django 5.0 on 2024-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0008_shaxarviloyattimeschange_tumantimeschange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shaxarviloyattimeschange',
            options={'verbose_name': 'Shaxar/Viloyat namoz vaqtlarini oʻzgartirish', 'verbose_name_plural': 'Shaxar/Viloyat vaqtlarini oʻzgartirish'},
        ),
        migrations.AlterModelOptions(
            name='tumantimeschange',
            options={'verbose_name': 'Tuman namoz vaqtlarini oʻzgartirish', 'verbose_name_plural': 'Tuman namoz vaqtlarini oʻzgartirish'},
        ),
        migrations.AddField(
            model_name='masjid',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='asr',
            field=models.CharField(help_text='Masjidda asr namozi oʻqilish vaqti', max_length=255, verbose_name='Asr'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='bomdod',
            field=models.CharField(help_text='Masjidda bomdod namozi oʻqilish vaqti', max_length=255, verbose_name='Bomdod'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='hufton',
            field=models.CharField(help_text='Masjidda xufton namozi oʻqilish vaqti', max_length=255, verbose_name='Xufton'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='peshin',
            field=models.CharField(help_text='Masjidda peshin namozi oʻqilish vaqti', max_length=255, verbose_name='Peshin'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='shom',
            field=models.CharField(help_text='Masjidda shom namozi oʻqilish vaqti', max_length=255, verbose_name='Shom'),
        ),
    ]
