# Generated by Django 5.0.1 on 2024-01-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0009_alter_shaxarviloyattimeschange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mintaqa',
            name='viloyat',
            field=models.CharField(choices=[('1', 'Toshkent shahri'), ('2', 'Andijon'), ('3', 'Buxoro'), ('4', 'Fargʻona'), ('5', 'Jizzax'), ('6', 'Namangan'), ('7', 'Navoiy'), ('8', 'Qashqadaryo'), ('9', 'Qoraqalpogʻiston'), ('10', 'Samarqand'), ('11', 'Sirdaryo'), ('12', 'Surxondaryo'), ('13', 'Toshkent viloyati'), ('14', 'Xorazm'), ('99', 'Boshqa')], help_text='Mintaqa joylashgan viloyat', max_length=255, verbose_name='Viloyat'),
        ),
    ]
