# Generated by Django 5.0.1 on 2024-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0010_alter_mintaqa_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masjid',
            name='asr',
            field=models.CharField(blank=True, default='00:00', help_text='Masjidda asr namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Asr'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='bomdod',
            field=models.CharField(blank=True, default='00:00', help_text='Masjidda bomdod namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Bomdod'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='hufton',
            field=models.CharField(blank=True, default='00:00', help_text='Masjidda xufton namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Xufton'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='peshin',
            field=models.CharField(blank=True, default='00:00', help_text='Masjidda peshin namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Peshin'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='shom',
            field=models.CharField(blank=True, default='00:00', help_text='Masjidda shom namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Shom'),
        ),
    ]
