# Generated by Django 5.0.1 on 2024-01-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0011_alter_masjid_asr_alter_masjid_bomdod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shaxarviloyattimeschange',
            options={'verbose_name': 'Viloyat vaqtlarini oʻzgartirish', 'verbose_name_plural': 'Viloyat vaqtlarini oʻzgartirish'},
        ),
        migrations.AlterModelOptions(
            name='tumantimeschange',
            options={'verbose_name': 'Tuman (shahar) vaqtlarini oʻzgartirish', 'verbose_name_plural': 'Tuman (shahar) vaqtlarini oʻzgartirish'},
        ),
    ]
