# Generated by Django 5.0.1 on 2024-01-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0012_alter_shaxarviloyattimeschange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman(shahar)', 'verbose_name_plural': 'Tuman(shahar)lar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
    ]
