# Generated by Django 5.0.1 on 2024-01-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0013_alter_district_options_alter_region_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Faol bo'lmasa foydalanuvchilar ro'yxatida ko'rinmaydi", verbose_name='Faolmi?'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Faol bo'lmasa foydalanuvchilar ro'yxatida ko'rinmaydi", verbose_name='Faolmi?'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Faol bo'lmasa foydalanuvchilar ro'yxatida ko'rinmaydi", verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_cyrl',
            field=models.CharField(blank=True, help_text='Tuman(shahar)ning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Tuman(shahar)ning ruscha nomi', max_length=255, null=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_uz',
            field=models.CharField(help_text='Tuman(shahar)ning lotincha nomi', max_length=255, verbose_name='Lotin'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(help_text='Tuman(shahar) joylashgan viloyat', on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='district',
            field=models.ForeignKey(help_text='Masjid joylashgan tuman(shahar)', on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.district', verbose_name='Tuman(shahar)'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='last_update',
            field=models.DateTimeField(verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_cyrl',
            field=models.CharField(blank=True, help_text='Viloyatning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Viloyatning ruscha nomi', max_length=255, null=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_uz',
            field=models.CharField(help_text='Viloyatning lotincha nomi', max_length=255, verbose_name='Lotin'),
        ),
    ]
