# Generated by Django 5.0.2 on 2024-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0016_alter_changedistricttimeschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='asr_jamoat',
            field=models.CharField(blank=True, help_text='Masjidda asr namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Asr jamoati'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='asr_type',
            field=models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Asr vaqti turi'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='bomdod_jamoat',
            field=models.CharField(blank=True, help_text='Masjidda bomdod namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Bomdod jamoati'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='bomdod_type',
            field=models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Bomdod vaqti turi'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='hufton_jamoat',
            field=models.CharField(blank=True, help_text='Masjidda xufton namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Xufton jamoati'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='hufton_type',
            field=models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Xufton vaqti turi'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='peshin_jamoat',
            field=models.CharField(blank=True, help_text='Masjidda peshin namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Peshin jamoati'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='peshin_type',
            field=models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Peshin vaqti turi'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='shom_jamoat',
            field=models.CharField(blank=True, help_text='Masjidda shom namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Shom jamoati'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='shom_type',
            field=models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Shom vaqti turi'),
        ),
    ]
