# Generated by Django 5.0.2 on 2024-02-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0018_shaxarviloyattimeschange_asr_jamoat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='asr_jamoat',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='asr_type',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='bomdod_jamoat',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='bomdod_type',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='hufton_jamoat',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='hufton_type',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='peshin_jamoat',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='peshin_type',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='shom_jamoat',
        ),
        migrations.RemoveField(
            model_name='shaxarviloyattimeschange',
            name='shom_type',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='asr_jamoat',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='asr_type',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='bomdod_jamoat',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='bomdod_type',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='hufton_jamoat',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='hufton_type',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='peshin_jamoat',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='peshin_type',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='shom_jamoat',
        ),
        migrations.RemoveField(
            model_name='tumantimeschange',
            name='shom_type',
        ),
        migrations.CreateModel(
            name='ChangeJamoatVaqtlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_district', models.BooleanField()),
                ('change_region', models.BooleanField()),
                ('change_masjid', models.BooleanField()),
                ('bomdod_type', models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Bomdod vaqti turi')),
                ('bomdod_jamoat', models.CharField(blank=True, help_text='Masjidda bomdod namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Bomdod jamoati')),
                ('peshin_type', models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Peshin vaqti turi')),
                ('peshin_jamoat', models.CharField(blank=True, help_text='Masjidda peshin namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Peshin jamoati')),
                ('asr_type', models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Asr vaqti turi')),
                ('asr_jamoat', models.CharField(blank=True, help_text='Masjidda asr namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Asr jamoati')),
                ('shom_type', models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Shom vaqti turi')),
                ('shom_jamoat', models.CharField(blank=True, help_text='Masjidda shom namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Shom jamoati')),
                ('hufton_type', models.CharField(choices=[('dynamic', 'Dinamik'), ('static', 'Statik')], default='dynamic', max_length=255, verbose_name='Xufton vaqti turi')),
                ('hufton_jamoat', models.CharField(blank=True, help_text='Masjidda xufton namozi oʻqilish vaqti', max_length=255, null=True, verbose_name='Xufton jamoati')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.district', verbose_name='Tuman')),
                ('masjid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.masjid', verbose_name='Masjid')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.region', verbose_name='Viloyat')),
            ],
        ),
    ]
