# Generated by Django 5.0.2 on 2024-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0020_alter_masjid_asr_jamoat_alter_masjid_bomdod_jamoat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changejamoatvaqtlari',
            name='change_all',
            field=models.BooleanField(default=False),
        ),
    ]
