# Generated by Django 5.0.2 on 2024-02-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0022_alter_changejamoatvaqtlari_asr_jamoat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changejamoatvaqtlari',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='changejamoatvaqtlari',
            name='masjid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.masjid', verbose_name='Masjid'),
        ),
        migrations.AlterField(
            model_name='changejamoatvaqtlari',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.region', verbose_name='Viloyat'),
        ),
    ]
