# Generated by Django 5.0.2 on 2024-02-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0024_alter_changejamoatvaqtlari_change_all_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changejamoatvaqtlari',
            options={'verbose_name': 'Jamoat vaqtini tahrirlash', 'verbose_name_plural': 'Jamoat vaqtlarini tahrirlash'},
        ),
    ]
