# Generated by Django 4.2.5 on 2024-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jamoatnamozlariapp", "0025_alter_changejamoatvaqtlari_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="changedistricttimeschedule",
            name="is_notify",
            field=models.BooleanField(
                choices=[(True, "Ha"), (False, "Yo'q")],
                default=False,
                help_text="Obunachilarga xabar yuborilsinmi?",
                verbose_name="Xabar yuborish",
            ),
        ),
        migrations.AddField(
            model_name="changemasjidtimeschedule",
            name="is_notify",
            field=models.BooleanField(
                choices=[(True, "Ha"), (False, "Yo'q")],
                default=False,
                help_text="Obunachilarga xabar yuborilsinmi?",
                verbose_name="Xabar yuborish",
            ),
        ),
        migrations.AddField(
            model_name="changeregiontimeschedule",
            name="is_notify",
            field=models.BooleanField(
                choices=[(True, "Ha"), (False, "Yo'q")],
                default=False,
                help_text="Obunachilarga xabar yuborilsinmi?",
                verbose_name="Xabar yuborish",
            ),
        ),
    ]
