# Generated by Django 4.2.5 on 2024-03-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jamoatnamozlariapp", "0026_changedistricttimeschedule_is_notify_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakbirVaqtlari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bomdod",
                    models.CharField(
                        blank=True,
                        help_text="Masjidda bomdod namozi oʻqilish vaqti",
                        max_length=255,
                        null=True,
                        verbose_name="Bomdod jamoati",
                    ),
                ),
                (
                    "peshin",
                    models.CharField(
                        blank=True,
                        help_text="Masjidda peshin namozi oʻqilish vaqti",
                        max_length=255,
                        null=True,
                        verbose_name="Peshin jamoati",
                    ),
                ),
                (
                    "asr",
                    models.CharField(
                        blank=True,
                        help_text="Masjidda asr namozi oʻqilish vaqti",
                        max_length=255,
                        null=True,
                        verbose_name="Asr jamoati",
                    ),
                ),
                (
                    "shom",
                    models.CharField(
                        blank=True,
                        help_text="Masjidda shom namozi oʻqilish vaqti",
                        max_length=255,
                        null=True,
                        verbose_name="Shom jamoati",
                    ),
                ),
                (
                    "hufton",
                    models.CharField(
                        blank=True,
                        help_text="Masjidda xufton namozi oʻqilish vaqti",
                        max_length=255,
                        null=True,
                        verbose_name="Xufton jamoati",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jamoatnamozlariapp.district",
                        verbose_name="Tuman",
                    ),
                ),
                (
                    "masjid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jamoatnamozlariapp.masjid",
                        verbose_name="Masjid",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jamoatnamozlariapp.region",
                        verbose_name="Viloyat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jamoat vaqtini tahrirlash",
                "verbose_name_plural": "Jamoat vaqtlarini tahrirlash",
            },
        ),
    ]
