# Generated by Django 4.2.5 on 2024-03-15 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("jamoatnamozlariapp", "0028_remove_takbirvaqtlari_masjid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="takbirvaqtlari",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
