# Generated by Django 4.2.5 on 2024-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0031_custommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masjid',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='location',
            field=models.URLField(blank=True, help_text='Masjid manzili', null=True, verbose_name='Manzil'),
        ),
    ]
