# Generated by Django 4.2.5 on 2024-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0032_masjid_latitude_masjid_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masjid',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='masjid',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='masjid',
            name='location',
            field=models.CharField(blank=True, help_text='Masjid manzili', max_length=300, null=True, verbose_name='Manzil'),
        ),
    ]
