# Generated by Django 4.2.11 on 2024-05-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "jamoatnamozlariapp",
            "0033_remove_masjid_latitude_remove_masjid_longitude_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="masjid",
            old_name="qisqa_tavsif",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="asr",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="asr_jamoat",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="asr_type",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="bomdod",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="bomdod_jamoat",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="bomdod_type",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="hufton",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="hufton_jamoat",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="hufton_type",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="last_update",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="peshin",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="peshin_jamoat",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="peshin_type",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="photo_file",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="shom",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="shom_jamoat",
        ),
        migrations.RemoveField(
            model_name="masjid",
            name="shom_type",
        ),
        migrations.AlterField(
            model_name="masjid",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtMosque",
                to="jamoatnamozlariapp.district",
                verbose_name="Tuman",
            ),
        ),
        migrations.AlterField(
            model_name="masjid",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faolmi?"),
        ),
        migrations.AlterField(
            model_name="masjid",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Masjid manzili",
                max_length=500,
                null=True,
                verbose_name="Manzil",
            ),
        ),
        migrations.AlterField(
            model_name="masjid",
            name="name_cyrl",
            field=models.CharField(
                default="Masjid",
                help_text="Masjidning krillcha nomi",
                max_length=255,
                verbose_name="Kirill",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="masjid",
            name="name_ru",
            field=models.CharField(
                default="Masjid",
                help_text="Masjidning ruscha nomi",
                max_length=255,
                verbose_name="Rus",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="masjid",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Masjidning rasmi",
                null=True,
                upload_to="imageMosque",
                verbose_name="Rasm",
            ),
        ),
    ]
