# Generated by Django 4.2.5 on 2024-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jamoatnamozlariapp", "0034_rename_qisqa_tavsif_masjid_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Foydalanuvchi ismi",
                null=True,
                verbose_name="Ismi",
            ),
        ),
    ]
