# Generated by Django 4.2.11 on 2024-05-05 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jamoatnamozlariapp", "0034_rename_qisqa_tavsif_masjid_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bomdod",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Bomdod"
                    ),
                ),
                (
                    "quyosh",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Quyosh"
                    ),
                ),
                (
                    "peshin",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Peshin"
                    ),
                ),
                (
                    "asr",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Asr"),
                ),
                (
                    "shom",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Shom"),
                ),
                (
                    "hufton",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Xufton"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Sana")),
            ],
            options={
                "verbose_name": "Namoz vaqti",
                "verbose_name_plural": "Namoz vaqtlari",
            },
        ),
        migrations.CreateModel(
            name="TakbirTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bomdod",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Bomdod"
                    ),
                ),
                (
                    "quyosh",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Quyosh"
                    ),
                ),
                (
                    "peshin",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Peshin"
                    ),
                ),
                (
                    "asr",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Asr"),
                ),
                (
                    "shom",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Shom"),
                ),
                (
                    "hufton",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Xufton"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Takbir vaqti",
                "verbose_name_plural": "Takbir vaqtlari",
            },
        ),
        migrations.CreateModel(
            name="IntervalTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bomdod",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Bomdod"
                    ),
                ),
                (
                    "quyosh",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Quyosh"
                    ),
                ),
                (
                    "peshin",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Peshin"
                    ),
                ),
                (
                    "asr",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Asr"),
                ),
                (
                    "shom",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Shom"),
                ),
                (
                    "hufton",
                    models.TimeField(
                        default=datetime.time(0, 0), verbose_name="Xufton"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districtIntervalTime",
                        to="jamoatnamozlariapp.district",
                        verbose_name="Tuman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Takbir vaqti",
                "verbose_name_plural": "Takbir vaqtlari",
            },
        ),
    ]
