# Generated by Django 4.2.11 on 2024-05-05 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("prayer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervaltime",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Sana"
            ),
        ),
        migrations.AlterField(
            model_name="prayertime",
            name="date",
            field=models.DateField(verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="takbirtime",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Sana"
            ),
        ),
    ]
