# Generated by Django 4.2.11 on 2024-05-12 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prayer", "0002_alter_intervaltime_date_alter_prayertime_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intervaltime",
            options={
                "verbose_name": "Viloyat namoz vaqti farqi",
                "verbose_name_plural": "Viloyat namoz vaqti farqlari",
            },
        ),
    ]
