# Generated by Django 4.2.5 on 2024-06-04 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prayer", "0003_alter_intervaltime_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="takbirtime",
            name="quyosh",
        ),
    ]
