#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

#exec /usr/local/bin/gunicorn namozvaqtlari.asgi --bind 0.0.0.0:8002 --chdir=/app -k uvicorn.workers.UvicornWorker
gunicorn namozvaqtlari.wsgi:application --bind 0.0.0.0:8001 --reload
