#!/bin/bash

set -o errexit
set -o nounset


#exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'

exec watchfiles --filter python celery.__main__.main --args '-A namozvaqtlari.celery_app worker -l INFO -Q my_sequential_queue -c 1 --time-limit=14400'